#include <stdio.h>

#define CSIZE 3		// Z+ && x < 4, 1-3
#define NSIZE 17	// Z+ && x <= 16, 0-16
#define MSIZE 9	// C*C, 9 combinations

//Varuables and Sets
struct 
Pair
{
	int val1;
	int val2;
};

struct 
GameState 
{
	/* Applicable Sets */
	int C[CSIZE];
	int N[NSIZE];
	struct Pair M[MSIZE];
	
	/* System Variables */
	
	// V = {true, flase}, represented with 1 or 0
	int good;
	int go;
	int start;
	int over;
	int found;
	
	// N
	int val;
	
	// subsets of M
	struct Pair R[MSIZE];
	struct Pair B[MSIZE];
	struct Pair S[MSIZE];
	struct Pair T[MSIZE];
	struct Pair F[MSIZE];
};

//Set utilities
int
equalPos (struct Pair pair1, struct Pair pair2)
{
	int isEqual;
	
	if(pair1.val1 == pair2.val1 && pair1.val2 == pair2.val2)
		isEqual = 1;
	else
		isEqual = 0;
		
	return isEqual;
}

int
containsInt (int val, int set[], int size) //1 means pair1 contains pair 2, 0 otherwise
{
	int i, 
		contains = 0;
	
	for (i = 0; i < size; i++)
	{
		if(set[i] == val)
			contains = 1;
	}
	
	return contains;
}

int
containsPair (struct Pair set[], struct Pair val, int size) //1 means pair1 contains pair 2, 0 otherwise
{
	int i, 
		contains;
	
	for (i = 0; i < size; i++)
	{
		if (equalPos(set[i], val) == 1)
			contains = 1;
		else
			contains = 0;
	} 
	
	return contains;
}

void
addPair (struct Pair set[], struct Pair val, int *size)
{
	int contains = containsPair(set, val, *size);
	
	if(contains == 0 && *size < MSIZE) //errors if the pair is a member of the set
	{
		(*size)++;
		set[*size - 1] = val;
	}
	else
	{
		printf("Error: Set already contains pair");
	}
}

void
removePair (struct Pair set[], struct Pair val, int *size)
{
	int contains = containsPair(set, val, *size),
		i,
		posI;
	
	if(contains == 1) //errors if the pair is not a member of the set
	{
		for (i=0; i < *size; i++)
		{
			if(equalPos(set[i], val) == 1)
				posI = i;
		}
		
		for (i = posI; i < *size; i++)
			set[i] = set[i + 1];
			
		(*size)--;
	}
	else
	{
		printf("Error: Set does not contain pair");
	}
}

//initialize variables
void
initGameState(struct GameState *game)
{
	int i, j, k = 0;

	// Initialize C = {1, 2, 3}
	for(i = 0; i < CSIZE; i++)
		game->C[i] = i + 1;

	// Initialize N : {0, 1... 16}
	for(i = 0; i < NSIZE; i++)
		game->N[i] = i;

	// Initialize M = C*C
	for(i = 0; i < CSIZE; i++)
	{
		for(j = 0; j < CSIZE; j++)
		{
			game->M[k].val1 = game->C[i];
			game->M[k].val2 = game->C[j];
			k++;
		}
	}

	// Initialize true/false
	game->good = 0;
	game->go = 0;
	game->start = 0;
	game->over = 0;
	game->found = 0;
	game->val = 0;
}

int
main() //TEST VALUES GENERATED BY OPENAI AND WILL NOT BE PART OF FINAL VERSION
{
struct Pair p1 = {1,2};
	struct Pair p2 = {1,2};
	struct Pair p3 = {2,3};

	struct Pair set[MSIZE];
	int size = 0;

	int ints[5] = {1,2,3,4,5};
	int i;

	printf("Testing equalPos\n");
	printf("p1 vs p2: %d\n", equalPos(p1,p2));
	printf("p1 vs p3: %d\n\n", equalPos(p1,p3));


	printf("Testing containsInt\n");
	printf("Contains 3: %d\n", containsInt(3, ints, 5));
	printf("Contains 9: %d\n\n", containsInt(9, ints, 5));


	printf("Testing addPair\n");
	addPair(set, p1, &size);
	addPair(set, p3, &size);

	printf("Set after adding:\n");
	for(i = 0; i < size; i++)
		printf("(%d,%d) ", set[i].val1, set[i].val2);
	printf("\n\n");


	printf("Testing containsPair\n");
	printf("Contains p1: %d\n", containsPair(set, p1, size));
	printf("Contains p2: %d\n\n", containsPair(set, p2, size));


	printf("Testing removePair\n");
	removePair(set, p1, &size);

	printf("Set after removing p1:\n");
	for(i = 0; i < size; i++)
		printf("(%d,%d) ", set[i].val1, set[i].val2);

	printf("\n");

	return 0;
}


